version: '3.8'
services: 
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: anothai.soon@northbkk.ac.th
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8080:80"

  backend: 
    container_name: backend_node
    build: .
    ports:
      - "5000:5000"